version: 2

updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "ivuorinen"
    assignees:
      - "ivuorinen"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    # Group security updates
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security-update"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "ivuorinen"
    assignees:
      - "ivuorinen"
    commit-message:
      prefix: "fix(github-action)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 3
    reviewers:
      - "ivuorinen"
    assignees:
      - "ivuorinen"
    commit-message:
      prefix: "fix(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
