# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"

run:
  timeout: 5m
  go: "1.23"

linters:
  default: standard

  enable:
    # Additional linters beyond standard
    - misspell
    - gocyclo
    - goconst
    - gocritic
    - revive
    - bodyclose
    - contextcheck
    - errname
    - exhaustive
    - forcetypeassert
    - nilerr
    - nolintlint
    - prealloc
    - godot
    - predeclared
    - lll
    - gosec
    - nlreturn

  disable:
    # Disable noisy linters
    - funlen
    - gocognit
    - nestif
    - cyclop
    - wsl
    - wrapcheck

  settings:
    lll:
      line-length: 120
    misspell:
      locale: US
    gocyclo:
      min-complexity: 10
    goconst:
      min-len: 2
      min-occurrences: 3

formatters:
  enable:
    - gofmt
    - goimports
    - golines

  settings:
    golines:
      max-len: 120
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'
    goimports:
      local-prefixes:
        - github.com/ivuorinen/gh-action-readme

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
  fix: true
