// Package appconstants provides common constants used throughout the application.
package appconstants

import "time"

// Exit code constants.
const (
	// ExitCodeError is the exit code for errors.
	ExitCodeError = 1
)

// Action type constants.
const (
	// ActionTypeComposite is the composite action type.
	ActionTypeComposite = "composite"
	// ActionTypeJavaScript is the JavaScript action type.
	ActionTypeJavaScript = "javascript"
	// ActionTypeDocker is the Docker action type.
	ActionTypeDocker = "docker"
	// ActionTypeInvalid is the invalid action type for testing.
	ActionTypeInvalid = "invalid"
	// ActionTypeMinimal is the minimal action type for testing.
	ActionTypeMinimal = "minimal"
)

// Update type constants for version comparison.
const (
	// UpdateTypeNone indicates no update is needed.
	UpdateTypeNone = "none"
	// UpdateTypeMajor indicates a major version update.
	UpdateTypeMajor = "major"
	// UpdateTypeMinor indicates a minor version update.
	UpdateTypeMinor = "minor"
	// UpdateTypePatch indicates a patch version update.
	UpdateTypePatch = "patch"
	// UpdateTypeDigest indicates a commit-SHA-pinned dependency whose pin differs
	// from the latest release's SHA. The semver bump magnitude is unknowable from
	// a SHA, so it is reported as a digest update rather than misclassified.
	UpdateTypeDigest = "digest"
)

// Timeout constants for API operations.
const (
	// APICallTimeout is the timeout for API calls.
	APICallTimeout = 10 * time.Second
	// CacheDefaultTTL is the default cache time-to-live.
	CacheDefaultTTL = 1 * time.Hour
)

// Version validation constants.
const (
	// FullSHALength is the full commit SHA length.
	FullSHALength = 40
	// MinSHALength is the minimum commit SHA length.
	MinSHALength = 7
	// VersionPartsCount is the number of parts in semantic versioning.
	VersionPartsCount = 3
)

// Cache key prefix constants.
const (
	// CacheKeyLatest is the cache key prefix for latest versions.
	CacheKeyLatest = "latest:"
	// CacheKeyRepo is the cache key prefix for repository data.
	CacheKeyRepo = "repo:"
	// CacheKeyTagSHA is the cache key prefix for a resolved tag->commit-SHA lookup.
	CacheKeyTagSHA = "tagsha:"
)

// Scope level constants.
const (
	// ScopeGlobal is the global scope.
	ScopeGlobal = "global"
	// ScopeUnknown is the unknown scope.
	ScopeUnknown = "unknown"
	// RedactedPlaceholder replaces secret values (e.g. GitHub tokens) when a
	// config is printed, so they never leak to terminals, CI logs, or screen shares.
	RedactedPlaceholder = "***redacted***"
)

// User input constants.
const (
	// InputYes is the yes confirmation input.
	InputYes = "yes"
	// InputAll is the all input option.
	InputAll = "all"
	// InputDryRun is the dry-run input option.
	InputDryRun = "dry-run"
)

// Regex patterns.
const (
	// RegexGitSHA is the regex pattern for git SHA.
	RegexGitSHA = "^[a-f0-9]{7,40}$"
)

// Token prefixes for validation.
const (
	// TokenPrefixGitHubPersonal is the GitHub personal access token prefix.
	TokenPrefixGitHubPersonal = "ghp_" // #nosec G101 -- token prefix pattern, not a credential
	// TokenPrefixGitHubPAT is the GitHub PAT prefix.
	TokenPrefixGitHubPAT = "github_pat_" // #nosec G101 -- token prefix pattern, not a credential
	// TokenFallback is the fallback token value.
	TokenFallback = "fallback-token" // #nosec G101 -- test value, not a credential
)

// Section markers for output.
const (
	// SectionDetails is the details section marker.
	SectionDetails = "\nDetails:"
	// SectionSuggestions is the suggestions section marker.
	SectionSuggestions = "\nSuggestions:"
)

// URL patterns.
const (
	// URLPatternGitHubRepo is the GitHub repository URL pattern.
	URLPatternGitHubRepo = "%s/%s"
)

// Template placeholder constants for Git repository information.
const (
	// DefaultOrgPlaceholder is the default organization placeholder.
	DefaultOrgPlaceholder = "your-org"
	// DefaultRepoPlaceholder is the default repository placeholder.
	DefaultRepoPlaceholder = "your-repo"
	// DefaultUsesPlaceholder is the default uses statement placeholder.
	DefaultUsesPlaceholder = "your-org/your-action@v1"
)

// Common message templates.
const (
	// MsgConfigHeader is the config file header.
	MsgConfigHeader = "# gh-action-readme configuration file\n"
	// MsgConfigWizardHeader is the config wizard header.
	MsgConfigWizardHeader = "# Generated by the interactive configuration wizard\n\n"
	// MsgConfigurationExportedTo is the configuration exported to success message.
	MsgConfigurationExportedTo = "Configuration exported to: %s"
)

// Version tag constants.
const (
	// VersionTagV1 is the default version tag fallback.
	VersionTagV1 = "v1"
	// VersionRefV1 is the default version reference with @ prefix.
	VersionRefV1 = "@v1"
)

// GitHub Actions permission level constants.
const (
	// PermissionRead is the read permission level.
	PermissionRead = "read"
	// PermissionWrite is the write permission level.
	PermissionWrite = "write"
	// PermissionScopeAll is the reserved global scope produced by the
	// `permissions: read-all` / `write-all` scalar shorthand.
	PermissionScopeAll = "all"
	// PermissionNone is the "no access" permission level.
	PermissionNone = "none"
	// PermScopeActions is the actions permission scope.
	PermScopeActions = "actions"
	// PermScopeChecks is the checks permission scope.
	PermScopeChecks = "checks"
	// PermScopeContents is the contents permission scope.
	PermScopeContents = "contents"
	// PermScopeDeployments is the deployments permission scope.
	PermScopeDeployments = "deployments"
	// PermScopeIssues is the issues permission scope.
	PermScopeIssues = "issues"
	// PermScopePackages is the packages permission scope.
	PermScopePackages = "packages"
	// PermScopePages is the pages permission scope.
	PermScopePages = "pages"
	// PermScopePullRequests is the pull-requests permission scope.
	PermScopePullRequests = "pull-requests"
	// PermScopeRepositoryProjects is the repository-projects permission scope.
	PermScopeRepositoryProjects = "repository-projects"
	// PermScopeSecurityEvents is the security-events permission scope.
	PermScopeSecurityEvents = "security-events"
	// PermScopeStatuses is the statuses permission scope.
	PermScopeStatuses = "statuses"
	// PermScopeAttestations is the attestations permission scope.
	PermScopeAttestations = "attestations"
	// PermScopeDiscussions is the discussions permission scope.
	PermScopeDiscussions = "discussions"
	// PermScopeIDToken is the id-token permission scope.
	PermScopeIDToken = "id-token"
)

// Node runtime constants.
const (
	// NodeRuntimeNode12 is the legacy Node.js 12 runtime (removed by GitHub January 2024).
	NodeRuntimeNode12 = "node12"
	// NodeRuntimeNode16 is the legacy Node.js 16 runtime (deprecated by GitHub).
	NodeRuntimeNode16 = "node16"
	// NodeRuntimeNode20 is the current Node.js 20 runtime identifier.
	NodeRuntimeNode20 = "node20"
	// NodeRuntimeNode24 is the Node.js 24 runtime identifier.
	NodeRuntimeNode24 = "node24"
)

// Label constants.
const (
	// LabelGitHubAction is the label for GitHub Action badges and metadata.
	LabelGitHubAction = "GitHub Action"
)

// Workflow type constants.
const (
	// ActivityWorkflowType is the activity icon used in default branding.
	ActivityWorkflowType = "activity"
)
