name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      - name: Install dependencies
        run: go mod tidy
      - name: Run unit tests
        run: go test ./...
      - name: Example Action Readme Generation
        run: |
          go run . gen --config config.yaml
        working-directory: ./testdata/example-action

