name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Install dependencies
        run: go mod tidy
      - name: Run unit tests
        run: go test ./...
      - name: Example Action Readme Generation
        run: |
          go run . gen --config config.yaml
        working-directory: ./testdata/example-action

