name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v4.2.2
      - name: Set up Go
        uses: actions/setup-go@v5 # v5.5.0
      - name: Install dependencies
        run: go mod tidy
      - name: Setup Node.js for EditorConfig tools
        uses: actions/setup-node@v4 # v4.4.0
        with:
          node-version: '18'
      - name: Install EditorConfig tools
        run: npm install -g eclint
      - name: Check EditorConfig compliance
        run: eclint check .
      - name: Run unit tests
        run: go test ./...
      - name: Example Action Readme Generation
        run: |
          go run . gen --config config.yaml
        working-directory: ./testdata/example-action
