---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint Code Base

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  Linter:
    name: PR Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      actions: write
      contents: write
      issues: write
      packages: read
      pull-requests: write
      statuses: write

    steps:
      - name: Run PR Lint
        # https://github.com/ivuorinen/actions
        uses: ivuorinen/actions/pr-lint@4360ea39c744dbd52bf1d624bf058ba4dd81245a # v2026.03.09
