---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Stale

on:
  schedule:
    - cron: "0 8 * * *" # Every day at 08:00
  workflow_call:
  workflow_dispatch:

permissions: {}

jobs:
  stale:
    name: 🧹 Clean up stale issues and PRs
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: ivuorinen/actions/stale@f7725f210c6740ae8042fbe89f2024dabad8a535 # v2026.07.11
        with:
          token: ${{ github.token }}
